[template]
src = "server.json.tmpl"
dest = "/opt/rancher/config/server.json"
owner = "root"
mode = "0644"
keys = [
  "/self/service/containers",
  "/containers",
  "self/container/name",
  "/self/container/primary_ip",
  "/self/container/service_index",
]
